<?php
return [
    'coming_soon' => 'Hamarosan',
    'details' => 'Részletek',
    'program' => [
        'toggle_label' => 'FIFI május 18. napirend',
        'schedule' => [
            ['time' => '09:15–10:00', 'title' => 'Regisztráció'],
            ['time' => '10:00–10:05', 'title' => 'Konferencia megnyitó'],
            ['time' => '10:05–12:15', 'title' => 'Plenáris előadások'],
        ],
        'plenary_talks' => [
            ['speaker' => 'Prof. Dr. Palkovics László', 'title' => 'Elnök, MI Tanács'],
            ['speaker' => 'Dr. Viktor Dorfler',          'title' => 'Professor of AI Strategy, University of Strathclyde'],
            ['speaker' => 'Prof. Dr. Aczél Petra',       'title' => 'Vezető, AI- és Jövőstratégiák Központ, Széchenyi István Egyetem'],
            ['speaker' => 'Prof. Dr. Gitta Kutyniok',    'title' => 'Chair for Mathematical Foundations of AI, Ludwig-Maximilians-Universität München (online)'],
            ['speaker' => 'Hidvégi Péter',               'title' => 'Ügyvezető igazgató, SAP Hungary'],
            ['speaker' => 'Kovács Gergely',              'title' => 'Vezető, XR Koalíció'],
        ],
        'schedule_after' => [
            ['time' => '12:15–13:00', 'title' => 'Ebédszünet'],
            ['time' => '13:00–13:15', 'title' => 'Sajtótájékoztató'],
            ['time' => '13:15–16:20', 'title' => 'Szekció-előadások, kerekasztal-beszélgetések (Kávészünet: 14:35–14:50)'],
            ['time' => '16:20–16:30', 'title' => 'Záróbeszéd – Dr. Dietz Ferenc, Elnök, Gábor Dénes Egyetem | Prompt Battle eredményhirdetés'],
        ],
        'sections_label' => 'Szekció-előadások és kerekasztal-beszélgetések',
        'sections' => [
            [
                'number'   => 1,
                'title'    => 'Deep Tech & Fintech',
                'speakers' => [
                    ['name' => 'Nagy Zsombor',       'role' => 'Vezető, MI központ, OTP Bank Nyrt., MI központvezető'],
                    ['name' => 'Rezka Norhafizah',   'role' => 'Junior researcher, Indonéz Kalimantan Islamic University (online)'],
                    ['name' => 'Dr. Vajda Viktor',    'role' => 'Főtitkár, MI Tanács'],
                    ['name' => 'Jendrolovics Máté',  'role' => 'CEO, Intuitech'],
                    ['name' => 'Kuthy Antal',         'role' => 'Ügyvezető, E-Group ICT Software Zrt.'],
                ],
                'roundtable' => [
                    'title'     => 'Kerekasztalbeszélgetés – Fintech trendek az Agentic AI fókuszával',
                    'moderator' => 'Dr. Urbán Viktor',
                    'speakers'  => [],
                ],
            ],
            [
                'number'   => 2,
                'title'    => 'Tudás, Kutatás, Technológia',
                'speakers' => [
                    ['name' => 'Csurgó Dávid',    'role' => 'Ügyvezető, GDE MIT'],
                    ['name' => 'Biczó Zoltán',    'role' => 'Óraadó oktató, Gábor Dénes Egyetem'],
                    ['name' => 'Jakab Dávid',     'role' => 'Óraadó oktató, Gábor Dénes Egyetem'],
                    ['name' => 'Dr. Urbán Viktor', 'role' => 'Fintech szakfelelős, Gábor Dénes Egyetem'],
                    ['name' => 'Szerémy Tamás',   'role' => 'Chief Technology Officer, GDE MIT'],
                    ['name' => 'Budaházy Gábor',  'role' => 'Head of Data and Analytics, GDE MIT'],
                ],
                'roundtable' => [
                    'title'     => 'Kerekasztal-beszélgetés',
                    'moderator' => 'Biczó Zoltán',
                    'speakers'  => [
                        ['name' => 'Gönczy László',  'role' => 'Tanszékvezető, BME MI tanszék'],
                        ['name' => 'Gulyás László',  'role' => 'Docens, ELTE MI tanszék'],
                        ['name' => 'Eigner György',  'role' => 'Dékán, Óbudai Egyetem'],
                    ],
                ],
            ],
        ],
    ],
    'speakers' => [
        [
            'name' => 'Prof. Dr. Palkovics László',
            'title' => 'Elnök',
            'institution' => 'MI Tanács',
            'image' => 'palkovics.jpg',
            'bio' => 'Prof. Dr. Palkovics László a mesterséges intelligenciáért felelős kormánybiztos. Korábban az Innovációs és Technológiai Minisztérium (2018–2022), majd a Technológiai és Ipari Minisztérium (2022) minisztereként tevékenykedett. Gépészmérnöki végzettséggel rendelkezik, és jelentős tisztséget vállalt az akadémiai és az ipari szféra meghatározó intézményeiben – többek között a Budapesti Műszaki és Gazdaságtudományi Egyetemen, az MTA SZTAKI-ban és a Knorr-Bremse vállalatnál. Szakmai fókuszában az innovációs politika, a felsőoktatás és az ipari K+F állnak. Kulcsszerepet játszott Magyarország mesterséges intelligencia stratégiájának kidolgozásában és a technológiai modernizáció előmozdításában. Mérnöki és innovációs munkásságát számos rangos elismeréssel jutalmazták, köztük a Széchenyi- és a Gábor Dénes-díjjal.',
            'image_position' => 'center top',
            'image_scale' => '80%',
        ],
        [
            'name' => 'Dr. Viktor Dörfler',
            'title' => 'Professor of AI Strategy',
            'institution' => 'University of Strathclyde Business School, Glasgow',
            'image' => 'dorfler.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr Viktor Dörfler is a scholar, consultant, teacher, and speaker, a Professor of AI Strategy at the University of Strathclyde Business School, Glasgow, UK and holds a Research Professor position at the Corvinus University of Budapest, Hungary, as well as a Visiting Professor appointment at the University of Zagreb, Croatia. As a practitioner, Viktor spearheaded the development of AI software, designed intelligent platforms, and conducted a number of AI implementations. Meanwhile, his scholarly research focuses on talent, creativity, and the grandmaster-apprentice relationship. Viktor conducted in-depth open-ended interviews with 20 top scientists, including 17 Nobel Laureates, in order to understand the thinking of scientists at the highest level of mastery. He advises organisations how to get the balance right between using AI, fostering communities of practice, and enabling grandmaster-apprentice relationships. Viktor\'s book What Every CEO Should Know About AI was published by the Cambridge University Press in 2022 followed by the Turkish edition in 2023.',
        ],
        [
            'name' => 'Hidvégi Péter',
            'title' => 'Ügyvezető igazgató',
            'institution' => 'SAP Hungary',
            'image' => 'hidvegi.png',
            'bio' => 'Az SAP Hungary ügyvezető igazgatója, Hidvégi Péter több mint húszéves tapasztalattal rendelkezik a technológiai és tanácsadói szektorban. 2017 óta dolgozik az SAP-nál, ahol vezetőként többek között a közüzemi, energia- és gyógyszeripari szektorért, majd a nagyvállalati ügyfelekért felelős értékesítési területet irányította, olyan vállalatokkal együttműködve, mint a MOL, az MVM, a Richter vagy az Egis. Korábban a PricewaterhouseCoopers, az IBM és az Accenture tanácsadója volt, később pedig a Microsoft régiós együttműködését vezette a távközlési szektor egyik legnagyobb szereplőjével. Műszaki diplomáját a BME-n, MBA fokozatát a Budapesti Corvinus Egyetemen szerezte, öt gyermek édesapja.',
        ],
        [
            'name' => 'Prof. Dr. Aczél Petra',
            'title' => 'Vezető',
            'institution' => 'AI- és Jövőstratégiák Központ, Széchenyi István Egyetem',
            'image' => 'aczel.png',
            'bio' => '',
        ],
        [
            'name' => 'Kovács Gergely',
            'title' => 'Elnök',
            'institution' => 'XR Koalíció',
            'image' => 'kovacs_g.png',
            'bio' => '',
        ],
        [
            'name' => 'Prof. Dr. Gitta Kutyniok',
            'title' => 'Chair for Mathematical Foundations of AI',
            'institution' => 'Ludwig-Maximilians-Universität München',
            'image' => 'gitta.png',
            'bio' => '',
        ],
    ],
];
