<?php
return [
    'coming_soon' => 'Hamarosan',
    'details' => 'Részletek',
    'program' => [
        'toggle_label' => 'Program',
        'schedule' => [
            ['time' => '09:15–10:00', 'title' => 'Regisztráció'],
            ['time' => '10:00–10:05', 'title' => 'Rektori köszöntő', 'speaker' => 'Zimány Krisztina'],
            ['time' => '10:05–12:15', 'title' => 'Plenáris előadások'],
        ],
        'plenary_talks' => [
            ['time' => '10:05–10:30', 'speaker' => 'Dr. Viktor Dörfler',         'title' => 'Professor of AI Strategy, University of Strathclyde',                       'talk_title' => 'AI and Sustainability'],
            ['time' => '10:30–10:50', 'speaker' => 'Hidvégi Péter',              'title' => 'Ügyvezető igazgató, SAP Hungary',                                            'talk_title' => 'SAP innovációk AI alapon, KKV-k innováció'],
            ['time' => '10:50–11:10', 'speaker' => 'Prof. Dr. Aczél Petra',      'title' => 'kommunikációkutató, egyetemi tanár, Széchenyi István Egyetem',              'talk_title' => 'AI-használati írástudás, AI-használat jövőkészségei'],
            ['time' => '11:10–11:30', 'speaker' => 'Prof. Dr. Palkovics László', 'title' => 'Egyetemi tanár, Debreceni Egyetem / GDE',                                    'talk_title' => 'AI strategy of Hungary and competitive perspectives in global economy'],
            ['time' => '11:30–11:50', 'speaker' => 'Dr. Dorota Czajkowska',      'title' => 'Academic teacher, Uczelnia Techniczno-Handlowa Warszawa',                   'talk_title' => 'From Data to Decisions: The Role of Artificial Intelligence in Public Finance Management'],
            ['time' => '11:50–12:10', 'speaker' => 'Kovács Gergely',             'title' => 'Elnök, XR Koalíció',                                                         'talk_title' => 'Teaching the Future: AI Vibecoding and the New Creative Power of Educators'],
        ],
        'schedule_after' => [
            ['time' => '12:15–13:00', 'title' => 'Ebédszünet'],
            ['time' => '13:00–13:15', 'title' => 'Sajtótájékoztató'],
            ['time' => '13:15–16:20', 'title' => 'Szekció-előadások, kerekasztal-beszélgetések (Kávészünet: 14:35–14:50)'],
            ['time' => '16:20–16:30', 'title' => 'Záróbeszéd – Dr. Dietz Ferenc, Elnök, Gábor Dénes Egyetem | Prompt Battle eredményhirdetés'],
        ],
        'sections_label' => 'Szekció-előadások és kerekasztal-beszélgetések',
        'sections' => [
            [
                'number'   => 1,
                'title'    => 'Deep Tech & Fintech',
                'room'      => 'Gábor Dénes Előadó',
                'moderator' => 'Urbán Viktor',
                'speakers' => [
                    ['time' => '13:00–13:15', 'name' => 'Dr. Dietz Ferenc',    'role' => 'Elnök',                        'institution' => 'Gábor Dénes Egyetem',                  'talk_title' => 'Sajtótájékoztató'],
                    ['time' => '13:15–13:35', 'name' => 'Nagy Zsombor',        'role' => 'MI központvezető',              'institution' => 'OTP Bank Nyrt.',                       'talk_title' => ''],
                    ['time' => '13:35–13:55', 'name' => 'Rezka Norhafizah',    'role' => 'Junior researcher',             'institution' => 'Indonéz Kalimantan Islamic University', 'talk_title' => '', 'online' => true],
                    ['time' => '13:55–14:15', 'name' => 'Dr. Vajda Viktor',    'role' => 'Főtitkár',                     'institution' => 'MI Tanács',                             'talk_title' => 'AI ügynökök szabályozása'],
                    ['time' => '14:15–14:35', 'name' => 'Rákosi Bálint',       'role' => 'CEO',                          'institution' => 'R-Szoft Kft.',                          'talk_title' => 'Agentic AI in Process Testing'],
                    ['time' => '14:35–14:50', 'name' => 'Kávészünet',          'role' => '',                              'institution' => '',                                      'talk_title' => '', 'break' => true],
                    ['time' => '14:50–15:20', 'name' => 'Urbán Viktor',        'role' => 'Kerekasztal – moderátor',      'institution' => '',                                      'talk_title' => 'Fintech Trends in the era of Agentic AI'],
                    ['time' => '15:20–15:40', 'name' => 'Bátorfi Botond',      'role' => 'Senior Innovation Consultant', 'institution' => 'Dorsum',                                'talk_title' => 'Strategic Autonomy in the Management World – A Working Solution From Europe'],
                    ['time' => '15:40–16:00', 'name' => 'Kuthy Antal',         'role' => 'Ügyvezető',                    'institution' => 'eGroup',                                'talk_title' => ''],
                    ['time' => '16:00–16:20', 'name' => 'Szilágyi Benedek',    'role' => 'Co-Founder',                   'institution' => '@1337 Partners',                        'talk_title' => 'AI in finance and banking'],
                    ['time' => '16:20–16:30', 'name' => 'Dr. Dietz Ferenc',    'role' => 'Elnök',                        'institution' => 'Gábor Dénes Egyetem',                   'talk_title' => 'Összefoglaló gondolatok, köszönetnyilvánítás valamint Prompt Battle eredményhirdetés'],
                ],
                'roundtable' => ['title' => '', 'moderator' => '', 'speakers' => []],
            ],
            [
                'number'   => 2,
                'title'    => 'Tudás, Kutatás, Technológia',
                'room'      => 'Nemes Tihamér terem',
                'moderator' => 'Biczó Zoltán',
                'speakers' => [
                    ['time' => '13:15–13:35', 'name' => 'Csurgó Dávid',    'role' => 'Ügyvezető',                         'institution' => 'GDE MIT', 'talk_title' => 'MI JÖVÜNK! GDE MIT projektek és kutatások összefoglalója'],
                    ['time' => '13:35–13:55', 'name' => 'Pápai Bálint',    'role' => 'Prompt specialista',                'institution' => 'GDE MIT', 'talk_title' => 'MI eszközök és lehetőségek a tanulásban (promptolás, chatbot)'],
                    ['time' => '13:55–14:15', 'name' => 'Biczó Zoltán',    'role' => 'Oktató',                            'institution' => 'GDE',     'talk_title' => ''],
                    ['time' => '14:15–14:35', 'name' => 'Jakab Dávid',     'role' => 'Oktató',                            'institution' => 'GDE',     'talk_title' => 'A promptolás kora véget ér; Az agentic AI hatása a tudásmunkára, az oktatásra és az ember-gép együttműködés új modelljei'],
                    ['time' => '14:35–14:50', 'name' => 'Kávészünet',      'role' => '',                                  'institution' => '',         'talk_title' => '', 'break' => true],
                    ['time' => '14:50–15:10', 'name' => 'Urbán Viktor',    'role' => 'GDE fintech specializáció felelős', 'institution' => 'GDE',     'talk_title' => 'GDE fintech specializáció bemutatása'],
                    ['time' => '15:10–15:40', 'name' => 'Kerekasztal – Biczó Zoltán vezetésével', 'role' => 'Résztvevők: Gönczy László (BME MI tanszékvezető), Gulyás László (ELTE MI tanszék docens), Eigner György (OE dékán)', 'institution' => '', 'talk_title' => '', 'roundtable' => true],
                    ['time' => '15:40–16:00', 'name' => 'Szerémy Tamás',   'role' => 'Chief Technology Officer',          'institution' => 'GDE MIT', 'talk_title' => 'Hackaton nyertes use case-ek bemutatása'],
                    ['time' => '16:00–16:20', 'name' => 'Budaházy Gábor',  'role' => 'Head of Data & Analytics',          'institution' => 'GDE MIT', 'talk_title' => 'AI a Contact Centerekben, üzleti áttekintés'],
                ],
                'roundtable' => ['title' => '', 'moderator' => '', 'speakers' => []],
            ],
        ],
    ],
    'speakers' => [
        [
            'name' => 'Prof. Dr. Palkovics László',
            'title' => 'Egyetemi tanár',
            'institution' => 'Gábor Dénes Egyetem és Debreceni Egyetem',
            'image' => 'palkovics.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Prof. Dr. Palkovics László a közelmúltig mesterséges intelligenciáért felelős kormánybiztosként irányította Magyarország megújított mesterséges intelligencia-stratégiájának végrehajtását. Korábban az Innovációs és Technológiai Minisztérium (2018–2022), majd a Technológiai és Ipari Minisztérium (2022) minisztereként tevékenykedett. Gépészmérnöki végzettséggel rendelkezik, és jelentős tisztséget vállalt az akadémiai és az ipari szféra meghatározó intézményeiben – többek között a Budapesti Műszaki és Gazdaságtudományi Egyetemen, az MTA SZTAKI-ban és a Knorr-Bremse vállalatnál. Szakmai fókuszában az innovációs politika, a felsőoktatás és az ipari K+F állnak. Kulcsszerepet játszott Magyarország mesterséges intelligencia stratégiájának kidolgozásában és a technológiai modernizáció előmozdításában. Mérnöki és innovációs munkásságát számos rangos elismeréssel jutalmazták, köztük a Széchenyi- és a Gábor Dénes-díjjal.',
        ],
        [
            'name' => 'Dr. Viktor Dörfler',
            'title' => 'Professor of AI Strategy',
            'institution' => 'University of Strathclyde Business School, Glasgow',
            'image' => 'dorfler.jpg',
            'image_position' => 'center top',
            'image_scale' => '80%',
            'bio' => 'Dr Viktor Dörfler is a scholar, consultant, teacher, and speaker, a Professor of AI Strategy at the University of Strathclyde Business School, Glasgow, UK and holds a Research Professor position at the Corvinus University of Budapest, Hungary, as well as a Visiting Professor appointment at the University of Zagreb, Croatia. As a practitioner, Viktor spearheaded the development of AI software, designed intelligent platforms, and conducted a number of AI implementations. Meanwhile, his scholarly research focuses on talent, creativity, and the grandmaster-apprentice relationship. Viktor conducted in-depth open-ended interviews with 20 top scientists, including 17 Nobel Laureates, in order to understand the thinking of scientists at the highest level of mastery. He advises organisations how to get the balance right between using AI, fostering communities of practice, and enabling grandmaster-apprentice relationships. Viktor\'s book What Every CEO Should Know About AI was published by the Cambridge University Press in 2022 followed by the Turkish edition in 2023.',
        ],
        [
            'name' => 'Hidvégi Péter',
            'title' => 'Ügyvezető igazgató',
            'institution' => 'SAP Hungary',
            'image' => 'hidvegi.png',
            'bio' => 'Az SAP Hungary ügyvezető igazgatója, Hidvégi Péter több mint húszéves tapasztalattal rendelkezik a technológiai és tanácsadói szektorban. 2017 óta dolgozik az SAP-nál, ahol vezetőként többek között a közüzemi, energia- és gyógyszeripari szektorért, majd a nagyvállalati ügyfelekért felelős értékesítési területet irányította, olyan vállalatokkal együttműködve, mint a MOL, az MVM, a Richter vagy az Egis. Korábban a PricewaterhouseCoopers, az IBM és az Accenture tanácsadója volt, később pedig a Microsoft régiós együttműködését vezette a távközlési szektor egyik legnagyobb szereplőjével. Műszaki diplomáját a BME-n, MBA fokozatát a Budapesti Corvinus Egyetemen szerezte, öt gyermek édesapja.',
        ],
        [
            'name' => 'Prof. Dr. Aczél Petra',
            'title' => 'kommunikációkutató, egyetemi tanár, központvezető',
            'institution' => 'AI- és Jövőstratégiák Központ, Széchenyi István Egyetem',
            'image' => 'aczel.png',
            'bio' => 'Dr. Aczél Petra kommunikáció- és médiakutató, egyetemi tanár, a győri Széchenyi István University AI- és Jövőstratégiák Központjának vezetője. Számos hazai és külföldi egyetemmel dolgozik együtt, kutatási projekteket vezetett, valamint hét könyv és több mint 200 tudományos publikáció szerzője a nyilvános, médiabeli és digitális kommunikáció, továbbá a jövőkompetenciák és a jövőállóság tématerületein. Legújabb kutatásai a mesterséges intelligenciára és annak az emberi jövőre gyakorolt hatásaira irányulnak.',
        ],
        [
            'name' => 'Kovács Gergely',
            'title' => 'Elnök',
            'institution' => 'XR Koalíció',
            'image' => 'kovacs_g.png',
            'bio' => 'Dr. Kovács Gergely az XR Koalíció elnöke, valamint a Defence Innovation Research Institute (VIKI) XR Kiválósági Központjának vezetője. Kutatásai a virtuális valóság, a mesterséges intelligencia és a digitális iker technológiák területére fókuszálnak, különös tekintettel az immerszív tanulásra, a mesterséges intelligenciával támogatott avatároktatókra és az emberi teljesítmény vizsgálatára XR-környezetekben. Emellett az Európai Védelmi Ügynökségen belül XR- és szimulációs témájú nemzetközi együttműködési kezdeményezéseket vezet, támogatva az innovációt és a következő generációs képzési koncepciók fejlesztését Európa-szerte.',
        ],
        [
            'name' => 'Dr. Dorota Czajkowska',
            'title' => 'Egyetemi adjunktus',
            'institution' => 'UTH Uczelnia Techniczno-Handlowa',
            'image' => 'czajkowska.png',
            'bio' => 'Dr. Dorota Czajkowska közgazdász, a közpénzügyek gyakorlati szakembere és egyetemi oktató. A helyi önkormányzati szektorban dolgozik, ahol a város adósságpolitikájával, hitelképességi értékelésével és pénzügyi kockázatelemzésével foglalkozik. Szakmai érdeklődési területei közé tartozik az önkormányzati finanszírozás, az államadósság-kezelés, a pénzügyi intézményekkel való kapcsolatrendszer, a hitelminősítések, valamint a makrogazdasági bizonytalanság közszektorbeli döntéshozatalra gyakorolt hatása. Emellett a varsói University of Technology and Commerce oktatója, ahol közgazdasági és pénzügyi tárgyakat tanít. Oktatási és tudományos szemléletében a közpénzügyi gyakorlatot ötvözi a gazdaságelmélettel, különös figyelmet fordítva a valós adatokra, az aktuális makrogazdasági folyamatokra és a gyakorlati esettanulmányokra. Jelenlegi kutatási és oktatási területei közé tartozik a mesterséges intelligencia alkalmazása a közpénzügyi menedzsmentben, a gazdasági oktatásban, valamint a közszféra döntéstámogató folyamataiban.',
        ],
    ],
];
